A bunch of different stuff for a bunch of different issues
OpenGOAL-Mods/OG-NoOOJ-II pull request #48
Opened 2024-02-15 00:03 UTC by Majora12

Should likely contain all the changes I've made to my branch if I did this right.

2024-02-15 00:11 UTC, Zedb0T commented
Any chance we can get these conflicts cleaned up first? @Majora12

2024-02-15 00:38 UTC, Zedb0T commented
https://github.com/OpenGOAL-Mods/OG-NoOOJ-II/blob/581743b18e20d0bda03b835bed885ebbd14b1ef6/goal_src/jak2/engine/mods/mod-common-functions.gc#L120-L129

Double define

2024-02-15 00:58 UTC, Zedb0T requested changes

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/common_objs/elevator.gc
> +          (set! (-> collide-query action-mask) (collide-action solid rideable))
Add a tag here please

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +    :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
Undo this please

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                           :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
Same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                            :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
Same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +    :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                                 :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
Same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                                :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                              :target-speed 204800.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
Samme

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/engine/target/board/target-board.gc
> +                            :transv-max 266240.0 ;; OG:Jetboard/No OoJ Changed Max Jetboard Speed to 100 meters
same

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/meet-brutter/meet-brutter.gc
> +    ;;   penetrate-63
Is all of this needed? or is this leftover from testing?

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/meet-brutter/meet-brutter.gc
> +      )
Would be nice to have a comment explaining this a bit for future learners

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/meet-brutter/meet-brutter.gc
>        )
Im not really sure I understand this part here

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/meet-brutter/meet-brutter.gc
> +    ;; (('hit 'hit-flinch 'hit-knocked)
Nice, I like this. Can maybe tag and explain it a bit for future learners

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +(define-extern set-target-board-mods-speed (function float float none))
I do wonder if we can just add this in the board header file and get rid of these forward declarations

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +  (set-target-board-mods-speed 102400.0 143360.0)
I was going to look for ways to smuggle the speed out of these races and keep it for the whole game, but this seems pretty solid.

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +    (race-start (-> self info index) self #f) ;; OG:Jetboard No OoJ changed to #t
uh no u didnt

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +          (let ((v1-4 (handle->process (-> v1-2 board)))) ;; OG:Jetboard Replaced vehicle
Here you are setting `v1-4` to the value of `(-> *target* board board)` I wouldnt be surprised if this causes instabilities

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/city/traffic/vehicle/vehicle-util.gc
> +                      ;;   )
This is good, but shouldn't we also comment out the stuff that below that runs when you hit triangle?

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/common/race/vehicle-racer.gc
> +          (logtest? (-> *target* focus-status) (focus-status board)) ;; OG:Jetboard
I wonder if simplifying ` (logtest? (-> *target* focus-status) (focus-status board))` to a `on-board?` macro is worth it here

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/common/race/vehicle-racer.gc
>                                                               (speech-type speech-type-45)
This should check the mission instead of `*target*`

2024-02-15 00:58 UTC, Zedb0T commented on goal_src/jak2/levels/drill/drill-mech-master.gc
> +    ;(let ((v1-20 *target*))
This is fine, alternatively we could check for mech focus status instead

2024-02-15 01:11 UTC, Majora12 commented on goal_src/jak2/levels/city/meet-brutter/meet-brutter.gc
> +    ;;   penetrate-63
It was done in a failed to attempt to make the Lurkers un-knockable so I don't think it's needed

2024-02-17 02:05 UTC, dallmeyer commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +(define-extern set-target-board-mods-speed (function float float none))
ah yea thats prob a better place for it

2024-02-17 02:09 UTC, dallmeyer commented on goal_src/jak2/engine/target/board/board-states.gc
> +    ;(logior! (-> self control root-prim prim-core action) (collide-action can-ride))
do you remember what this change is affecting? its something in the jetboard grind state `target-board-ride-edge`

2024-02-17 02:16 UTC, dallmeyer commented on goal_src/jak2/levels/city/port/race/errol-chal.gc
> +          (let ((v1-4 (handle->process (-> v1-2 board)))) ;; OG:Jetboard Replaced vehicle
looks like its just checking the y coordinate, and if you're low enough you fail, think its okay

2024-02-17 02:28 UTC, dallmeyer commented on goal_src/jak2/levels/city/shuttle/shuttle.gc
> +    :default-hit-points 10000
are these changes for the uber missions, to make the citizens invincible ? (add comment)

2024-02-17 02:33 UTC, dallmeyer commented on goal_src/jak2/levels/city/traffic/vehicle/vehicle-util.gc
> +                      ;;   )
think this is my change, and yeah probably. I don't think it was triggering anything but still

2024-02-17 02:35 UTC, dallmeyer commented on goal_src/jak2/levels/common/race/vehicle-racer.gc
> +          (logtest? (-> *target* focus-status) (focus-status board)) ;; OG:Jetboard
oh there's a shorter macro
```suggestion
          (focus-test? *target* board) ;; OG:Jetboard
```

2024-02-18 00:11 UTC, merged